mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: silent
ipv6: false
geodata-mode: true
external-controller: 0.0.0.0:9090
external-ui: clash-dashboard/dist
tcp-concurrent: false
interface-name: ""
enable-process: false
geodata-loader: memconservative
secret: ""
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  force-domain:
    - '+'
  skip-domain:
    - 'google.com'
  port-whitelist:
    - 80
    - 443
    - 8000-9000
profile:
  store-selected: true
  store-fake-ip: false
dns:
  enable: true
  device: Meta
  ipv6: false
  default-nameserver: 
    - 8.8.8.8
    - 1.1.1.1
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['networktest.twilio.com', '+.twilio.com']
  nameserver:
    - 1.0.0.1
    # ISI IP BUG YANG KALIAN GUNAKAN 
  proxy-server-nameserver:
    - 1.0.0.1
    # ISI IP BUG YANG KALIAN GUNAKAN 
  fallback: []
  fallback-filter:
    geoip: false
    geoip-code: 'ID'
    geosite:
      - GFW
      - GREATFIRE
    domain: ['google.com']
    ipcidr: [240.0.0.0/4]
tun:
  enable: false
  device: Meta
  stack: system
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: false
iptables: {enable: false, inbound-interface: "", bypass: []}
hosts:
  'note.microsoft.com': 104.18.38.174
  'maps.google.com': 104.18.10.39
geox-url:
  mmdb: "https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb"
  geoip: "https://github.com/v2fly/geoip/raw/release/geoip-only-cn-private.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat"
tproxy-port: 9898
proxies:
proxy-providers:
  MasSam:
    type: file
    path: ./MasSam.yaml
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com/generate_204'
      interval: 2400
  MasSam2:
    type: file
    path: ./MasSam2.yaml
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com/generate_204'
      interval: 2400
  MasSam3:
    type: file
    path: ./MasSam3.yaml
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com/generate_204'
      interval: 2400
proxy-groups:
  - name: ğŸ¤–ğŸ¤–DARK-ITğŸ¤–ğŸ¤–
    type: load-balance
    strategy: round-robin
    disable-udp: false
    use:
      - MasSam
  - name: ğŸ¶ï¸StremingğŸ¶
    type: load-balance
    strategy: round-robin
    use:
      - MasSam2
  - name: ğŸ§‘â€ğŸ’»SosmedğŸ§‘â€ğŸ’»
    type: load-balance
    strategy: round-robin
    use:
      - MasSam3
  - name: ğŸ®GamingğŸ®
    type: load-balance
    strategy: round-robin
    use:
      - MasSam
  - name: "Adblock"
    type: select
    proxies:
      - REJECT
store-selected: true
store-fake-ip: true
use-host: true
enhanced-mode: fake-ip
listen: 0.0.0.0:7874
nameserver:
  - 192.168.8.1
  - 192.168.9.1
  - https://dns.adguard.com/dns-query
  - https://dns-google.com/dns-query
  - tls://dns.adguard.com
  - tls://dns-google.com/
  - 1.1.1.1
  - 8.8.8.8
fallback:
  - 1.0.0.1
  - https://dns.cloudflare.com/dns-query
  - https://dns.google/dns-query
  - 112.215.203.254
default-nameserver:
  - 1.1.1.1
  - 8.8.8.8
  - 112.215.203.254
fake-ip-range: 198.18.0.1/16
fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
rule-providers:
    Streaming:
      type: file
      behavior: classical
      path: ./Streaming.yaml
    Global:
      type: file
      behavior: classical
      path: ./Global.yaml
    Sosmed:
      type: file
      behavior: classical
      path: ./Sosmed.yaml
    Gaming:
      type: file
      behavior: classical
      path: ./Gaming.yaml
    Adblock:
      type: file
      behavior: classical
      path: ./Adblock.yaml
      
rules:
  - DST-PORT,7895,REJECT
  - DST-PORT,7892,REJECT
  - DST-PORT,7895,REJECT
  - DST-PORT,7892,REJECT
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - RULE-SET,Gaming,ğŸ®GamingğŸ®
  - RULE-SET,Streaming,ğŸ¶ï¸StremingğŸ¶
  - RULE-SET,Sosmed,ğŸ§‘â€ğŸ’»SosmedğŸ§‘â€ğŸ’»
  - RULE-SET,Adblock,REJECT
  - MATCH,ğŸ¤–ğŸ¤–DARK-ITğŸ¤–ğŸ¤–